# en el docker compose superior se define el valor por defecto para que nunca venga vacío
ARG IMG_BASE_NAME
FROM ${IMG_BASE_NAME}

# Arguments
ARG PYTHON_VER
ARG VENV_NAME
ARG RUFF_VER

# Set Python environment
RUN mkdir -p settings/dev
COPY docker/settings/dev/* settings/dev/
RUN bash ./settings/dev/install_uv.sh $PYTHON_VER $VENV_NAME $RUFF_VER