FROM docker.io/pacoalcaide/python-base:0.0.1

# Arguments
ARG PYTHON_VER
ARG VENV_NAME
ARG RUFF_VER

# Environment variables
#ENV VENV_NAME=$VENV_NAME
#ENV PYTHON_VER=$PYTHON_VER
#ENV RUFF_VER=$RUFF_VER

# Set Python environment
COPY install_uv.sh requirements.txt settings/
RUN bash ./settings/install_uv.sh $VENV_NAME $PYTHON_VER $RUFF_VER
# RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/root/.zsh_history && export HISTIGNORE='ls'" \
#     && echo "export HISTFILESIZE=1000" >> "/root/.bashrc"\
#     && echo "$SNIPPET" >> "/root/.zshrc"