#FROM docker.io/pacoalcaide/python-base:0.0.1
ARG IMG_BASE_NAME
FROM ${IMG_BASE_NAME:-pacoalcaide/python-base_vscode-python-uv-template:0.0.1}

# Arguments
ARG VENV_NAME
ARG PYTHON_VER
ARG RUFF_VER

# Set Python environment
RUN mkdir -p settings/dev
COPY settings/dev/* settings/dev/
RUN bash ./settings/dev/install_uv.sh $VENV_NAME $PYTHON_VER $RUFF_VER