services:
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile_Base
      args:
        - IMG_ORG=${IMAGE_ORIGEN}
        - QUARTO_VER=${QUARTO_VERSION}
        - USER_NAME=${USER_NAME}
        - USER_EMAIL=${USER_EMAIL}
    image: ${IMAGE_BASE_NAME}
    env_file:
      - .env

  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile_Dev
      args:
        - IMG_BASE_NAME=${IMAGE_BASE_NAME}
        - VENV_NAME=${VENV_NAME}
        - PYTHON_VER=${PYTHON_VERSION}
        - RUFF_VER=${RUFF_VERSION}
    image: ${IMAGE_DEV_NAME}
    depends_on:
      - base
    env_file:
      - .env
    volumes:
      - ..:/workspace
    command: sleep infinity
    working_dir: /workspace
    # ports:
    #   - "8888:8888"