services:
  dev:
    image: ${IMAGE_DEV_NAME}
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - IMG_ORG=${IMAGE_ORIGEN:-ubuntu:24.04}
        - QUARTO_VER=${QUARTO_VERSION}
        - USER_NAME=${USER_NAME}
        - USER_EMAIL=${USER_EMAIL}
        - PYTHON_VER=${PYTHON_VERSION}
        - VENV_NAME=${VENV_NAME}
        - RUFF_VER=${RUFF_VERSION}
    env_file:
      - .env
    volumes:
      - ..:/workspace
    command: sleep infinity
    working_dir: /workspace
    # ports:
    #   - "8888:8888"